# Cloudflare Pages 部署配置

name = "shadowing-learning"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages 函数配置
[[pages_functions]]
path = "/api/transcribe"

[[pages_functions]]
path = "/api/postprocess"

[[pages_functions]]
path = "/api/progress/*"

# 环境变量配置
[env.production.vars]
NEXT_PUBLIC_APP_URL = "https://your-domain.pages.dev"

[env.preview.vars]
NEXT_PUBLIC_APP_URL = "https://preview-domain.pages.dev"
