name = "umuo"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

# Environment variables for Cloudflare Pages
[env.production.vars]
NODE_ENV = "production"
