name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm build
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Install Wrangler globally
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: |
          echo "Checking environment variables..."
          echo "CLOUDFLARE_API_TOKEN length: ${#CLOUDFLARE_API_TOKEN}"
          echo "CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID"

          if [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "ERROR: CLOUDFLARE_API_TOKEN is not set"
            exit 1
          fi

          export CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN"
          export CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID"

          echo "Environment variables set, starting deployment..."
          wrangler pages deploy .next --project-name oumu-ai --commit-dirty
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Output deployment URLs
        run: |
          echo "🚀 Deployment completed!"
          echo "🌐 Live site: https://umuo.app"