name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: 'deploy-production'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-${{ steps.setup-node.outputs.node-version }}-
            ${{ runner.os }}-pnpm-

      - name: Setup Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.ts', '**/*.tsx', '**/*.jsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: |
          echo "🔒 Running security audit..."
          pnpm audit --audit-level high
          echo "✅ Security audit completed"

      - name: Build application
        run: pnpm build
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Optimize build for deployment
        run: |
          echo "Optimizing build directory for deployment..."
          # For standalone mode, prepare for Cloudflare Pages Functions
          if [ -d ".next/standalone" ]; then
            echo "Using standalone build output..."
            cp -r .next/standalone/* .next/
            cp -r public/* .next/ 2>/dev/null || true

            # Create worker for Next.js routing
            cat > .next/_worker.js << 'EOF'
// Cloudflare Pages Functions worker for Next.js standalone output
export default {
  async fetch(request, env, ctx) {
    try {
      // Import the Next.js server
      const { Server } = await import('./server.js');
      const server = new Server({
        hostname: 'localhost',
        port: 3000,
      });

      return server.handleRequest(request);
    } catch (error) {
      console.error('Error handling request:', error);
      return new Response('Internal Server Error', { status: 500 });
    }
  }
};
EOF
          fi

          # Clean up large cache files before deployment
          find .next -name "*.pack" -delete 2>/dev/null || true
          find .next -name "*.map" -delete 2>/dev/null || true
          rm -rf .next/cache .next/static/webpack 2>/dev/null || true

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: oumu-ai
          directory: .next
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Enable compatibility mode for Next.js API routes
          compatibility-date: 2024-01-01
          compatibility-flags: nodejs_compat

      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Deployment completed!"
          echo "🌐 Live site: https://umuo.app"
          echo "📊 Deploy URL: ${{ steps.deploy.outputs.url }}"
          echo "📈 Deployment ID: ${{ steps.deploy.outputs.id }}"

          node .github/notify-deploy.js success \
            "${{ steps.deploy.outputs.url }}" \
            "${{ steps.deploy.outputs.id }}"
        env:
          NOTIFICATION_SERVICE: ${{ secrets.NOTIFICATION_SERVICE }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          node .github/notify-deploy.js failure
        env:
          NOTIFICATION_SERVICE: ${{ secrets.NOTIFICATION_SERVICE }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}